### ISSUE TITLE
添加推特关注时提示“推特ID不存在或网络错误！”

### ISSUE THREAD

**Issue by Aperove** [mobyw/nonebot-twitter-guild#2]
我这边配置好了以后，给bot发送推特关注命令，会提示 [推特ID不存在或网络错误！]
但是服务器本身就在国外，我在思考是不是data_source.py当中Bearer 或者 第46行api地址的问题，
对不起我非常新手，没怎么接触过编程……不知道您能不能教教我，我可以请您喝杯咖啡🙏

**Comment by mobyw** [comment]
请查看并提供发送指令后 nonebot 后台的 log 信息

另外，本项目的原项目已停止维护，为方便后期维护建议使用 [ELF_RSS](https://github.com/Quan666/ELF_RSS)

**Comment by mobyw** [comment]
我看到你 fork [`twitterAutoToken`](https://github.com/Aperove/twitterAutoToken) 仓库没有任何 Actions 运行记录，请先手动运行确保可用后开启自动获取 `Token`
