### ISSUE TITLE
报错： AttributeError: type object 'Event' has no attribute '__event__'

### ISSUE THREAD

**Issue by sakamataz** [mobyw/nonebot-twitter-guild#4]
![image](https://user-images.githubusercontent.com/44469959/176581813-6a6b3493-9d22-4d80-9e2e-5d31ef455c97.png)

**Comment by sakamataz** [comment]
nonebot版本是 2.0.0-beta.4

**Comment by mobyw** [comment]
可以把频道补丁文件删除，改为从 [nonebot-plugin-guild-patch](https://github.com/mnixry/nonebot-plugin-guild-patch) 引入。
另外 nonebot-twitter 项目原作者跑路了，建议换用 [ELF_RSS](https://github.com/Quan666/ELF_RSS)。

**Comment by sakamataz** [comment]
好的，感谢



在 2022-06-30 14:15:59，"mobyw" ***@***.***> 写道：

可以把频道补丁文件删除，改为从 nonebot-plugin-guild-patch 引入。
另外 nonebot-twitter 项目原作者跑路了，建议换用 ELF_RSS。
