### ISSUE TITLE
请问

### ISSUE THREAD

**Issue by nishinokaede** [mobyw/nonebot-twitter-guild#5]
![image](https://user-images.githubusercontent.com/78548970/185456251-092821d3-f253-4deb-88d9-ec64d9b42131.png)
请问这一步的具体操作应该是怎么做的呢 萌新拜托了

**Comment by mobyw** [comment]
删掉 `nonebot_guild_patch.py` ，安装 `nonebot-plugin-guild-patch`，其他文件中从 `nonebot_guild_patch` 导入的改为从 `nonebot_plugin_guild_patch` 导入。
